# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_commnet_poll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet_poll',
            new_name='Comment_poll',
        ),
    ]
