# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170214_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='avatat',
            field=models.ImageField(blank=True, default='avatar/default.png', max_length=256, upload_to='avatar/%Y/%m'),
        ),
    ]
